apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-dags
  namespace: airflow
data:
  example_dag.py: |
    from airflow import DAG
    from airflow.operators.dummy_operator import DummyOperator
    from datetime import datetime, timedelta

    default_args = {
        'owner': 'airflow',
        'depends_on_past': False,
        'start_date': datetime(2023, 1, 1),
        'email_on_failure': False,
        'email_on_retry': False,
        'retries': 1,
        'retry_delay': timedelta(minutes=5),
    }

    dag = DAG(
        'example_dag',
        default_args=default_args,
        description='A simple example DAG',
        schedule_interval=timedelta(days=1),
    )

    t1 = DummyOperator(
        task_id='dummy_task',
        dag=dag,
    )