# Airflow configuration
airflow:
  executor: CeleryExecutor
  fernetKey:   # Generate this with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
    secretName: airflow-fernet-key
    secretKey: fernet-key  
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "True"
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"

# Postgres configuration
postgresql:
  enabled: true

# Redis configuration
redis:
  enabled: true

# Persistence for logs
logs:
  persistence:
    enabled: true
    size: 1Gi

# DAGs persistence
dags:
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteMany
    # storageClass: "" # Specify your storage class here if needed

configMaps:
extraVolumeMounts:
  - name: dags
    mountPath: /opt/airflow/dags
    readOnly: true

extraVolumes:
  - name: dags
    configMap:
      name: airflow-dags


# Web server configuration
web:
  replicas: 1
  service:
    type: ClusterIP
    ports:
      - port: 8080
        targetPort: 8080
  webserverSecretKeySecretName: airflow-webserver-secret

# Scheduler configuration
scheduler:
  replicas: 1

# Worker configuration
workers:
  replicas: 1